### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by K232** [giansi/grav-plugin-cookies-policy#1]
Thanks a lot for this plugin, I'll add it soon to my site.
I've just noticed that you copied at least the readme from the error-plugin, because at the end there are lots of references to error, e.g. "bin/gpm update error". I did not update it on my own as I don't know whether the content also needs to be updated, e.g. is it for your plugin also necessary to delete the directory (in manual update) first?
Thanks!

**Comment by giansi** [comment]
Hi, thank you for reporting: it's fixed now. Glad you appreciate this plugin!

**Comment by K232** [comment]
Thanks a lot giansi!
