### ISSUE TITLE
deactivation gives error

### ISSUE THREAD

**Issue by cord** [giansi/grav-plugin-cookies-policy#2]
when inserting the tag {% include 'partials/cookiespolicy.html.twig' %} into the theme deactivation of the plugin crashes the site

**Comment by giansi** [comment]
Hi,
do you mean you added the tag {% include 'partials/cookiespolicy.html.twig' %} then you deactivated the plugin, setting enabled to false?

**Comment by cord** [comment]
yes, correct.

I would expect I can enable/disable the plugin w/o touching the theme again

**Comment by giansi** [comment]
AFAIK, "include" raises an error when the template is not found and there's no way to check if a template exists before including it. Have I missed something? Any other solution than include?

**Comment by giansi** [comment]
Fixed with 1.0.6 release. Thank you
