### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [giansi/grav-plugin-cookies-policy#4]
The plugin CookiesPolicy can't be configured using the new [Grav's Admin Panel](https://github.com/getgrav/grav-plugin-admin). For example, if we go to the settings page of the plugin (url `/admin/plugins/cookiespolicy`) and click on _Save_, there's the following error:

> **Validation failed:** type is not defined in blueprints

According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

My config: Grav v0.9.39, Admin Panel v0.4.2, CookiesPolicy v1.0.3

**Comment by giansi** [comment]
Fixed with last commit but forgot to close the issue
